### ISSUE TITLE
Retorno da lista sincronizada no TMDB

### ISSUE THREAD

**Issue by alexanderfdeveloper** [eggerco/cronica#18]
![image](https://github.com/MadeiraAlexandre/Cronica/assets/94754185/2cf74c34-e7f7-4851-9478-c15fe4f48973)

É uma limitação da API ou é um bug, só retorna 21, quando na verdade tem mais de 100 itens

**Comment by MadeiraAlexandre** [comment]
Eu ainda vou conferir isso em detalhes, mas me parece que não há paginação nas listas TMDb (Pelo menos na V4 da API). 
Planejo dar uma atenção maior a essa integração com TMDb na próxima versão (integrando com a tela de Lista e no seletor de lista).

**Comment by MadeiraAlexandre** [comment]
Corrigi a paginação na versão beta. Obrigado pelo report!
