### ISSUE TITLE
Bulk mark/unmark episodes

### ISSUE THREAD

**Issue by rithask** [eggerco/cronica#19]
**Is your feature request related to a problem? Please describe.**
Bulk mark if an episode or a season or a movie is watched or remove from watched. 

**Describe the solution you'd like**
A list of episodes and an edit button at the top to mark multiple episodes watched or remove from watched. The UI could look like the UI when deleting photos from iOS photos app. Each seasons can be split by sections and a check mark near the season title to make every episode in it. 

**Describe alternatives you've considered**

**Additional context**

**Comment by MadeiraAlexandre** [comment]
![Simulator Screenshot - iPhone 14 Pro - 2023-07-24 at 23 07 18](https://github.com/MadeiraAlexandre/Cronica/assets/33880764/f624778d-3c4d-4306-96f6-32adc5b74ac6)
In the meanwhile, the best way to do it is to use the context menu to mark an episode and all previous episodes as watched.
I really liked the description of the UI you've provided, it could be an awesome feature for power users, and I'll plan to add this to the app! Thank you!

**Comment by rithask** [comment]
Closing as it is solved temporarily. Thanks.
