### ISSUE TITLE
Sobre marcar como assistido

### ISSUE THREAD

**Issue by alexanderfdeveloper** [eggerco/cronica#20]
Sobre o comportamento em si, é muito difícil mudar? Sei que da para ativar marcar como assistido com um toque, mas é fácil você tocar sem querer, achando eu ia abrir as informações

![image](https://github.com/MadeiraAlexandre/Cronica/assets/94754185/43d492b7-c4cb-4535-8da2-3b74408f7fb0)

![image](https://github.com/MadeiraAlexandre/Cronica/assets/94754185/96dd529a-6f91-478d-b0a1-0b69d4ff67a2)

E você pode querer acessar a visualização completa, mas teria que procurar na lista.

A minha ideia seria: 

um toque você abriria como é hoje, e também ter uma opção para ver as informações completa em caso de querer mudar de lista ou compartilhar

E dois toque para marcar como assistido

Outra ideia em caso de assistir tudo, seria interessante mudar de lista para uma "Completados" por exemplo

Tenho 2 ideias: aparecer um seletor de lista ao marcar o último como assistido

Ou ter uma configuração para escolher um lista padrão ao marcar o último como assistido

**Comment by alexanderfsm** [comment]
Na minha opinião, a mesma ideia de ter uma configuração para aparecer a lista ao clicar em adicionar, seria mais interessante, ter um configuração para mostrar seletor de lista ao marcar o último como assistido, porque em uma lista padrão, vai que a pessoa tem lista separada de assistidos

**Comment by alexanderfsm** [comment]
No momento acho mais importante o comportamento ao marcar como assistido com 2 toque e ter a opção de visualização completa, porque ae poderia abrir o último episódio trocar de lista e depois marcar como assistido, sem precisar ficar procurando ele, pra fazer todo esse processo

**Comment by alexanderfsm** [comment]
Agora com esse novo update, ficou mais visível a opção ficar lista, é um bom recurso para às necessidades ditas acima 

![image](https://github.com/MadeiraAlexandre/Cronica/assets/94754185/8a31c9fa-3c63-435a-8adc-0f755faf9701)

**Comment by MadeiraAlexandre** [comment]
> Sobre o comportamento em si, é muito difícil mudar? Sei que da para ativar marcar como assistido com um toque, mas é fácil você tocar sem querer, achando eu ia abrir as informações

> E você pode querer acessar a visualização completa, mas teria que procurar na lista.

Por enquanto, o melhor jeito de fazer isso com essa configuração ativa é com menu de contexto. Quando ela está ativa, o app libera o menu de contexto para episódios que permite chamar a UI de detalhes do episódio.

> 
> A minha ideia seria: 
> 
> um toque você abriria como é hoje, e também ter uma opção para ver as informações completa em caso de querer mudar de lista ou compartilhar
> 
> E dois toque para marcar como assistido

Vou melhorar essa parte no próximo update com base no seu feedback.
