### ISSUE TITLE
Ordering of 'Up Next' episodes

### ISSUE THREAD

**Issue by rithask** [eggerco/cronica#28]
**Is your feature request related to a problem? Please describe.**
Ordering the episodes in 'Up Next' section in most recently marked/seen would be better than ordering it on alphabetical order. Because if the number of TV shows we are watching at the same time is increasing, it would be harder to find a TV show whose name starts with the last letters of english alphabet.

**Describe the solution you'd like**
Either default the ordering to most recently marked or give an option to order it as most recently watched or alphabetical order in the settings

**Describe alternatives you've considered**

**Additional context**

**Comment by MadeiraAlexandre** [comment]
I'll made this change in the next release, thanks!

**Comment by rithask** [comment]
Solved
