### ISSUE TITLE
Italian translations are wrong - Are you open for external help?

### ISSUE THREAD

**Issue by espositoandrea** [eggerco/cronica#32]
**Is your feature request related to a problem? Please describe.**
Italian translations are currently wrong and they’re hard to comprehend. For example “Secondo Gestocquotidiano destro” has a typo and is not easy to understand that it’s related to a scroll gesture. 

**Describe the solution you'd like**
If you are open to external help, I’m Italian (annd I’m fluent in English) so I would offer some translations!

**Describe alternatives you've considered**
The other feasible alternative is to just show users the English strings. 

**Additional context**
There’s no additional context. If you welcome some translations, please tell me if you want that I change a resource file or some other thing!

**Comment by MadeiraAlexandre** [comment]
Hello,

Thank you for reporting. Yes, I would love some help with the Italian translation.
If you want, you can make a list of every mistake, and I'll fix it in the resource file.
Can you also share your profile on any social media that you prefer? I like to add everyone that helped me with translations on the About screen. 🙏

Thank you. 😄

**Comment by kevinm6** [comment]
This should be fixed since latest release

**Comment by MadeiraAlexandre** [comment]
@kevinm6 thanks! I'll close the issue.
