### ISSUE TITLE
The "Explore" bar initially displays "Try Again Later"

### ISSUE THREAD

**Issue by dnicolson** [eggerco/cronica#39]
This is displayed before there are available recommendations:
<img width="1112" alt="Screenshot 2024-05-30 at 21 47 21" src="https://github.com/egger/cronica/assets/2276355/4a9b589d-3e91-41be-82f4-a07aa18614de">

Perhaps a different view could be displayed instead.

**Comment by MadeiraAlexandre** [comment]
Yes, this needs to be fixed to display a better message. 
Additionally, the app could programmatically set the "Explore" tab as the default if there are no recommendations available.

**Comment by MadeiraAlexandre** [comment]
Improved the wording about this message on the latest commit, it'll now display a proper message saying that there's no recommendations available with a button to quickly jump to the "Explore" section.
