### ISSUE TITLE
More options button doesn't work on iOS 18 

### ISSUE THREAD

**Issue by DeEskalator** [eggerco/cronica#41]
**Describe the bug**
When clicking more options (three dots) when looking at a movie (for instance to review it) on iOS 18 nothing happens. This didn't occur til I installed the iOS 18 beta. Also occurs on iPad OS 18

**To Reproduce**
1. Open any movie
2. Click on '...'
3. Nothing happens

**Expected behavior**
Seeing the additional options

**Comment by MadeiraAlexandre** [comment]
Fixed in the latest commit, I'll publish a TestFlight link on the [Twitter/X](https://x.com/CronicaApp) page when Apple approves the build. The App Store version will be updated as soon as iOS 18 SDK is allowed. 
Thank you for reporting! 🙏
